language: ruby
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build cs101F2019_syllabus.tex
deploy:
  provider: releases
  api_key:
    secure: pJx3GmUjkjTwl/TdZNy1q8w/RQvdWMVH1/kqxq7b7VfFoqjhTPv7jZBGvpCZiqogfXD1E/CU3Hc2M0xLU3Ffj/FKSdaFcN/K8AirHZ9fhZzNgidhT7Xhag6WnYgIzbe4s2vjyxdsX7U92lWAlgR4St9UzxteS7fm5lfruB/YWL+fV38gislo9D9wkj8ZBuUTFc0ZFLvWhxETiKk4/rk6THkcolVAkYu7/K4u1KJdvdmJ9IHuKx5aachnwre9D06QHuh2xmFBHC4TDaLxaawzRDb2Dj/8HtGRY8iBn49Wh4pHm6E3qpW6sMzJluPoQzG/LtAtqEaZt+RBxBjwLQQ3S66zXJQmq33mbKXhK+XGm0sfNDpdAuVRCfR5bgb77+fPI4nwdlRiUDPfAyuzPItywRCRZ71ul+l4YzpCEf8VsXfvUXtLfHafNfmUj+symiQgbFGqTg4+Q3evWESXamFbTqArc7FO4AYiaFDPcL6rqUY/q3borvabjOCyHk7d4fadBQvSLtNcSOGdHSi6iXQyexXrkYVoaXrn8G8DdYr8R2d0RtzNhQfNJGTS/otNvo4rJnvbxN12wS+uCHYhPnLcTMqZax3vK8+1TO/dfRGWCfdEogJTe6WCRMbICjpQ+oaZ7pWHRitNJozpqG+8ewV+6k/j4JJ8dt7fkdlEudErjIY=
  file: _build/cs101F2019_syllabus.pdf
  skip_cleanup: true
  on:
    tags: true
